### ISSUE TITLE
Document how to reproduce build result file size

### ISSUE THREAD

**Issue by porst17** [jet2jet/fluidsynth-emscripten#5]
This is more of a question respectively a request for documentation than a bug report. I tried building fluidsynth-emscripten myself using the [emsdk Docker image](https://hub.docker.com/r/emscripten/emsdk):

```
docker run -ti --rm -v $(pwd):/src -u $(id -u):$(id -g) emscripten/emsdk /bin/bash
```

Then, I used the following commands for building:
```
mkdir build
cd build
emcmake cmake -Denable-oss=off -DCMAKE_BUILD_TYPE=MinRelSize ..
emmake make
```

The build succeeds, but the file `libfluidsynth-2.2.1.js` is 1.1MB in size, which is much larger than what's offered in the releases of the repository (~670KB).

How can I reproduce the much smaller build?

**Comment by jet2jet** [comment]
Previously I used Emscripten 1.38.14 and I built the library with the simple command: `emcmake cmake ..` and `make -j16`.
Since I changed the build environment, I reproduced that the size of `libfluidsynth-2.2.1.js` is much larger.

I also found that build with `CMAKE_BUILD_TYPE=Release` makes the size smaller, so please use Release build type if you don't want debug information.
(I'll use Release build for the next library release.)
\# Updated README.md with commit 8a66977.

**Comment by porst17** [comment]
Thanks for your comments. When I noticed that my build was significantly larger compared to yours, I also noticed the `CMAKE_BUILD_TYPE` variable and I though I'd be clever and not go for `CMAKE_BUILD_TYPE=Release`, but for `CMAKE_BUILD_TYPE=MinSizeRel` because it promised to reduce the build size more than the `Release` type.

However, instead of `MinSizeRel`, I ended up typing `MinRelSize` in the terminal resulting in no reduction at all. See my post above. Stupid typo.

So I tested it again, now with the proper `CMAKE_BUILD_TYPE`. `Release` gives me a size similar to yours. However, `MinSizeRel` reduces the build size by another 20%. So maybe, you could consider using `MinSizeRel` over `Release` in your published builds. I did not check for any side effects on performance, though.
